use hr;

DROP TABLE IF EXISTS EMP;

CREATE TABLE EMP
(ID INT PRIMARY KEY,
DNAME VARCHAR(10),
CITY VARCHAR(20)
);

TRUNCATE TABLE EMP;
DROP PROCEDURE IF EXISTS INSERT_EMP;
DELIMITER //
CREATE PROCEDURE INSERT_EMP(IN EMPID INT, IN DEPT VARCHAR(10), IN CITY VARCHAR(20))
BEGIN
DECLARE CONTINUE HANDLER FOR 1062
BEGIN
SELECT CONCAT("Duplicate entry for the employee");
END;
INSERT INTO EMP VALUES(EMPID, DEPT, CITY);
SELECT * FROM EMP WHERE ID = EMPID;
END
//

DELIMITER ;
CALL INSERT_EMP(100, 'IT', 'PUNE');
SELECT * FROM EMP;

TRUNCATE TABLE EMP;
DROP PROCEDURE IF EXISTS INSERT_EMP;
DELIMITER //
CREATE PROCEDURE INSERT_EMP(IN EMPID INT, IN DEPT VARCHAR(10), IN CITY VARCHAR(20))
BEGIN
DECLARE EXIT HANDLER FOR 1062
SELECT CONCAT("Duplicate entry for the employee", EMPID) AS ERRORMESSAGE;
DECLARE EXIT HANDLER FOR SQLEXCEPTION SELECT "SQLEcxeption" AS ERRORMESSAGE;
DECLARE EXIT HANDLER FOR SQLSTATE "23000" SELECT 'SQLSTATE 23000' AS ERRORMESSAGE;
INSERT INTO EMP VALUES(EMPID, DEPT, CITY);
SELECT * FROM EMP WHERE ID = EMPID;
END
//

DELIMITER ;
CALL INSERT_EMP(100, 'IT', 'PUNE');
CALL INSERT_EMP(100, 'IT', 'PUNE');
-- SELECT * FROM EMP;

DELIMITER //
CREATE PROCEDURE CHL_EMPL(IN EMP_ID INT)
BEGIN
DECLARE c INT;
SELECT EMPLOYEE_ID INTO C FROM EMPLOYEES WHERE EMPLOYEE_ID = EMP_ID;
SELECT C;
IF C IS NULL THEN
SIGNAL SQLSTATE '45000'
SET MESSAGE_TEXT = 'EMPLOYEE NOT FOUND IN EMP';
END IF;
END
//

CALL CHL_EMPL(400);

DELIMITER // 
CREATE PROCEDURE GETDIVISION (IN NUMERATOR INT, IN DENOMINATOR INT, OUT RES DOUBLE)
BEGIN 
DECLARE DIVISION_BY_ZERO CONDITION FOR SQLSTATE '45000';
DECLARE CONTINUE HANDLER FOR DIVISION_BY_ZERO
RESIGNAL SET MESSAGE_TEXT = 'Denominstor cannot be zero';
IF DENOMINATOR = 0 THEN
SIGNAL DIVISION_BY_ZERO;
ELSE
SET RES:=NUMERATOR/DENOMINATOR;
END IF;
END
//

DELIMITER ;
CALL GETDIVISION(12, 5, @R);
SELECT @R;
CALL GETDIVISION(12, 0, @A);
SELECT @A;


DELIMITER // 
CREATE PROCEDURE EMP_CUR()
BEGIN 
DECLARE DONE INT DEFAULT FALSE;
DECLARE HIRE DATE;
DECLARE E_SAL DECIMAL(10, 2);
DECLARE EMP_CURSOR CURSOR FOR 
SELECT HIRE_DATE, SALARY FROM EMPLOYEES;
 -- DECLARE A HANDLER FOR 'THE NOTFOUND' CONDITION
DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = TRUE;
OPEN EMP_CURSOR;
READ_LOOP: LOOP
FETCH EMP_CURSOR INTO HIRE, E_SAL;
IF DONE THEN LEAVE READ_LOOP;
END IF;
IF E_SAL > 1000 AND HIRE > '1998-02-01'  THEN
SELECT CONCAT(FIRST_NAME, ' earns ', E_SAL, ' and joined the organization on ', HIRE) AS Employee_Info
            FROM EMPLOYEES 
            WHERE HIRE_DATE = HIRE AND SALARY = E_SAL;
END IF;
END LOOP;
CLOSE EMP_CURSOR;
END 
//
DELIMITER ;
CALL EMP_CUR();
SELECT CONCAT(FIRST_NAME, ' earns ', SALARY, ' and joined the organization on ' , HIRE_DATE) FROM EMPLOYEES WHERE SALARY>15000 AND HIRE_DATE > '1998-02-01';

DELIMITER // 
CREATE PROCEDURE empcount(id int)
BEGIN
DECLARE DID INT;
DECLARE C INT;
DECLARE DONE INT;
DECLARE C1 CURSOR FOR SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE ID=DEPARTMENT_ID;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = 1;
SET C =0;
OPEN C1;
LABEL: LOOP
FETCH C1 INTO DID;
IF DONE THEN LEAVE LABEL;
END IF;
SET C =C +1;
END LOOP;
CLOSE C1;
SELECT C;
END
//

DELIMITER ;
CALL EMPCOUNT(100);
create view v1 as
select last_name, department_name, job_title
from employees e, departments d , jobs j
where e.job_id=j.job_id and e.department_id=d.department_id; 

select * from v1;

