describe employees;
select * from employees;
select department_id from employees;
select distinct department_id from employees;
select distinct job_id, salary from employees;
select * from employees where department_id in (20, 30); -- can use or also in case of in for small amount of conditions
select * from employees where salary NOT BETWEEN 20000 and 30000;
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID FROM EMPLOYEES ORDER BY SALARY DESC;
SELECT * FROM EMPLOYEES WHERE COMMISSION_PCT IS null;
SELECT UPPER(FIRST_NAME) FROM EMPLOYEES;
SELECT SUM(SALARY), MAX(FIRST_NAME), MIN(LAST_NAME), AVG(PHONE_NUMBER) FROM EMPLOYEES;
-- THIS IS HOW YOU CAN COMMENT IN MYSQL
SELECT DEPARTMENT_ID, JOB_ID, SUM(SALARY) AS GROUPED_SALARY, MAX(SALARY) AS MAXIMUM, AVG(SALARY) AS AVERAGE FROM EMPLOYEES GROUP BY DEPARTMENT_ID, JOB_ID;

SELECT DEPARTMENT_ID, JOB_ID, SUM(SALARY) AS GROUPED_SALARY, MAX(SALARY) AS MAXIMUM, AVG(SALARY) AS AVERAGE 
FROM EMPLOYEES 
WHERE DEPARTMENT_ID IN (10, 20, 30)
GROUP BY DEPARTMENT_ID, JOB_ID
ORDER BY MAX(SALARY) DESC;

SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID < 40;
SELECT JOB_ID FROM EMPLOYEES WHERE JOB_ID LIKE 'S%';
SELECT * FROM EMPLOYEES WHERE COMMISSION_PCT IS NULL;
SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE LAST_NAME LIKE '__E%';
SELECT POWER(2, 4), TRUNCATE(234.45645, 3), ROUND(123.43635, 2);


