use hr;
select * from employees 
where hire_date 
between '2000-01-01' and '2000-12-31';

select LAST_NAME, JOB_ID, SALARY
FROM EMPLOYEES 
WHERE JOB_ID = 'SA_REP'
OR JOB_ID = 'AD_PRES'
AND SALARY > 15000;

select LAST_NAME, JOB_ID, SALARY
FROM EMPLOYEES 
WHERE (JOB_ID = 'SA_REP'
OR JOB_ID = 'AD_PRES')
AND SALARY > 15000;

CREATE TABLE  TEMP
(ID INT ,
NAME VARCHAR(20)
);

ALTER TABLE TEMP
ADD (BDATE DATE, SAL DECIMAL(10, 2));

ALTER TABLE TEMP
MODIFY COLUMN SAL DECIMAL(5, 2);

DROP TABLE TEMP;
DESCRIBE TEMP;

SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_ID =100;

UPDATE DEPARTMENTS 
SET MANAGER_ID = NULL 
WHERE DEPARTMENT_ID = 100;
SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_ID =100;
-- COMMIT;
ROLLBACK;
SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_ID =100;

INSERT INTO JOBS VALUE('ACACCOUNT1', 'Public Accountant',	4200,	9000);
savepoint ins;
SELECT * FROM jobs WHERE JOB_ID ='ACACCOUNT1';
DELETE FROM JOBS WHERE JOB_ID = 'ACACCOUNT1';
SELECT * FROM JOBS WHERE JOB_ID ='ACACCOUNT1';
COMMIT;
ROLLBACK TO INS;
SELECT * FROM JOBS WHERE JOB_ID ='ACACCOUNT1';
ROLLBACK;
SELECT * FROM JOBS WHERE JOB_ID ='ACACCOUNT1';

SELECT LOWER(LAST_NAME), UPPER(FIRST_NAME), CONCAT('Mrs/Ms ', FIRST_NAME, ' ', LAST_NAME), SUBSTR(JOB_ID, 4, 3), LPAD(LAST_NAME, 10, '*'), LENGTH(EMAIL), TRIM('K' FROM LAST_NAME)
FROM EMPLOYEES;

SELECT ABS(-1000), CEIL(1.23), FLOOR(1.23), SQRT(69), ROUND(45.1564165, 0);

SELECT TRIM(BOTH 'K' FROM 'KAKAK');
SELECT TRIM(TRAILING 'K' FROM 'KAKAK');
SELECT TRIM(LEADING 'K' FROM 'KAKAK'); 

DROP TABLE TAB2;
CREATE TABLE TAB2 AS SELECT DEPARTMENT_ID,  SUM(SALARY) , AVG(SALARY), MAX(SALARY), MIN(SALARY), COUNT(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID NOT between 10 AND 50 GROUP BY DEPARTMENT_ID;
SELECT * FROM TAB2;
SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES;
SELECT DATE_FORMAT(HIRE_DATE, '%D %M %Y') FROM EMPLOYEES;
SELECT DATEDIFF(CURDATE(), HIRE_DATE) FROM EMPLOYEES;
SELECT EXTRACT(DAY FROM HIRE_DATE) FROM EMPLOYEES;
SELECT DATE_ADD('2021-12-28 07:54:21', INTERVAL 500 MINUTE) ;
SELECT DATE_ADD(SYSDATE(),INTERVAL 20 MINUTE);
SELECT MAKEDATE(2028, 241);

DELIMITER // 

CREATE FUNCTION ADD_NUM(A INT, B INT)
RETURNS INT DETERMINISTIC
BEGIN 
RETURN A+B ;
END 
//

dELIMITER ;
SELECT ADD_NUM(10000000,6000);

DELIMITER //
CREATE FUNCTION EXP(ID INT)
RETURNS INT DETERMINISTIC
BEGIN
DECLARE DAT DATE;
SELECT HIRE_DATE INTO DAT FROM EMPLOYEES WHERE EMPLOYEE_ID = ID;
RETURN YEAR(CURRENT_date())-YEAR(DAT);
END //

SELECT EXP(EMPLOYEE_ID) FROM EMPLOYEES;