use hr;
DELIMITER //
CREATE PROCEDURE p_demo( num1 decimal)
BEGIN
IF num1 < 5000 THEN
SELECT 'SALARY LESS THAN 5000';
ELSEIF num1 BETWEEN 5000 AND 10000 THEN
SELECT 'SALARY BETWEEN 5000 AND 10000';
ELSE 
SELECT 'SALARY MORE THAN 10000';
END IF;
END //

DELIMITER ;
CALL P_DEMO(5000);

DELIMITER //
CREATE PROCEDURE SHOW_EMPLOYEE()
BEGIN
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_NAME, JOB_TITLE FROM EMPLOYEES  A, DEPARTMENTS B, JOBS C
WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID AND A.JOB_ID = C.JOB_ID;+
END //

DELIMITER ;
CALL SHOW_EMPLOYEE();

DELIMITER //
CREATE PROCEDURE P2(IN V_ID INT, OUT MAX_SAL INT)
BEGIN 
SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID FROM EMPLOYEES
WHERE DEPARTMENT_ID = V_ID;
SELECT MAX(SALARY) INTO MAX_SAL FROM EMPLOYEES;
END //
DELIMITER ;
CALL P2(80, @M);
SELECT @M;

DELIMITER //
CREATE PROCEDURE P1()
BEGIN
DECLARE MAX_SAL DECIMAL;
CALL P2(80, MAX_SAL);
SELECT MAX_SAL;
END //
DELIMITER ;
CALL P1();


DELIMITER //
CREATE PROCEDURE basic_loop(P1 INT)
BEGIN
LABEL1:
LOOP 
SET P1 = P1+1;
IF P1<5 THEN SELECT P1;
ITERATE LABEL1;
END IF;
LEAVE LABEL1;
END LOOP LABEL1;
SET @X = P1;
END
//

DELIMITER ;
CALL BASIC_LOOP(-1);
SELECT @X;

CREATE TABLE TI (A INT);
DELIMITER //
CREATE PROCEDURE b_loop(P1 INT)
BEGIN
LABEL1:
LOOP 
SET P1 = P1+1;
IF P1<5 THEN 
INSERT INTO TI VALUE (P1);
SELECT P1;
ITERATE LABEL1;
END IF;
LEAVE LABEL1;
END LOOP LABEL1;
SET @X = P1;
END
//

DELIMITER ;
CALL B_LOOP(-1);
SELECT @X;
SELECT * FROM TI;

DELIMITER // 
CREATE PROCEDURE REPEAT_LOOP(PI INT)
BEGIN 
SELECT PI;
SET @X = 0;

REPEAT
SET @X = @X+1;
SELECT @X;
UNTIL @X>PI END REPEAT;
END 
//

DELIMITER ;
CALL REPEAT_LOOP(10);

DELIMITER //
CREATE PROCEDURE WHILE_LOOP(P INT)
BEGIN
DECLARE V1 INT DEFAULT 5;
WHILE V1 > 0 DO
SELECT V1;
SET V1 = V1-1;
END WHILE;
END
//
DELIMITER ;
CALL WHILE_LOOP(12);

DELIMITER //
CREATE PROCEDURE EMP_loop(P1 INT)
BEGIN
DECLARE P INT;
SET P = 1;
LABEL1:
LOOP 
IF P<6 THEN 
SELECT JOB_ID, SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID = P1;
SET P1 = P1+1;
SET P = P+1;
ITERATE LABEL1;
END IF;
LEAVE LABEL1;
END LOOP LABEL1;
END
//
DELIMITER ;
CALL EMP_LOOP(104);


DELIMITER // 
CREATE FUNCTION CHK_SAL( V_ID INT)
RETURNS INT DETERMINISTIC
BEGIN
DECLARE V_SAL INT;
SELECT SALARY INTO V_SAL FROM EMPLOYEES WHERE EMPLOYEE_ID = V_ID;
IF V_SAL > 20000 THEN
RETURN 1;
ELSE 
RETURN 2;
END IF;
END //

DELIMITER ;
SELECT EMPLOYEE_ID, CHK_SAL(SALARY) FROM EMPLOYEES WHERE CHK_SAL(EMPLOYEE_ID) = 2;
USE HR;
UPDATE EMPLOYEES SET SALARY = SALARY+10000 WHERE CHK_SAL(EMPLOYEE_ID) = 2;
SELECT EMPLOYEE_ID, CHK_SAL(SALARY) FROM EMPLOYEES WHERE CHK_SAL(EMPLOYEE_ID) = 2;
 ROLLBACK;
 SELECT EMPLOYEE_ID, CHK_SAL(SALARY) FROM EMPLOYEES WHERE CHK_SAL(EMPLOYEE_ID) = 2;

SHOW PROCEDURE STATUS WHERE DB LIKE '%R%';
 DELIMITER // 
 CREATE PROCEDURE DISP_MGR(INOUT V_ID INT)
 BEGIN
 SELECT MANAGER_ID INTO V_ID
 FROM EMPLOYEES WHERE DEPARTMENT_ID = V_ID;
 END
 //
 DELIMITER ;
 SET @M = 100;
 CALL DISPL_MGR(@M);
 SELECT @M;