USE HR;
SELECT EMPLOYEE_ID, LAST_NAME, FIRST_NAME, SALARY,
CASE
WHEN SALARY < 2000 THEN 'Low'
WHEN SALARY >= 2000 AND SALARY < 5000 THEN 'Medium'
ELSE 'High'
END AS POSITION FROM EMPLOYEES;

DELIMITER // 
CREATE PROCEDURE PROCESS_DATA()
BEGIN 
DECLARE DONE INT DEFAULT FALSE;
DECLARE E_ID INT;
DECLARE E_SAL DECIMAL(10, 2);
DECLARE EMP_CURSOR CURSOR FOR 
SELECT EMPLOYEE_ID, SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID = 100;
 -- DECLARE A HANDLER FOR 'THE NOTFOUND' CONDITION
DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = TRUE;
OPEN EMP_CURSOR;
READ_LOOP: LOOP
FETCH EMP_CURSOR INTO E_ID, E_SAL;
IF DONE THEN LEAVE READ_LOOP;
END IF;
IF E_SAL > 5000 THEN
UPDATE EMPLOYEES SET SALARY = SALARY+1000
WHERE EMPLOYEE_ID = E_ID;
ELSEIF E_SAL = 24000 THEN
UPDATE EMPLOYEES SET SALARY = SALARY+0
WHERE EMPLOYEE_ID = E_ID;
ELSE
UPDATE EMPLOYEES SET SALARY = SALARY+500
WHERE EMPLOYEE_ID = E_ID;
END IF;
END LOOP;
CLOSE EMP_CURSOR;
END 
// 
DELIMITER ;
SELECT * FROM EMPLOYEES;
CALL PROCESS_DATA();
SELECT * FROM EMPLOYEES;

DELIMITER //
CREATE PROCEDURE PROC()
BEGIN 
DECLARE E_ID INT;
DECLARE E_SAL DECIMAL(10, 2);
SELECT EMPLOYEE_ID, SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID = 100;
SELECT E_ID, E_SAL;
END
//

DELIMITER ;
CALL PROC();


DELIMITER // 
CREATE PROCEDURE PROCESS_D()
BEGIN 
DECLARE DONE INT DEFAULT FALSE;
DECLARE E_ID INT;
DECLARE E_SAL DECIMAL(10, 2);
DECLARE EMP_CURSOR CURSOR FOR 
SELECT EMPLOYEE_ID, SALARY FROM EMPLOYEES WHERE DEPARTMENT_ID = 100;
 -- DECLARE A HANDLER FOR 'THE NOTFOUND' CONDITION
DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = TRUE;
OPEN EMP_CURSOR;
READ_LOOP: LOOP
FETCH EMP_CURSOR INTO E_ID, E_SAL;
IF DONE THEN LEAVE READ_LOOP;
END IF;
IF E_SAL > 5000 THEN
UPDATE EMPLOYEES SET SALARY = SALARY+1000
WHERE EMPLOYEE_ID = E_ID;
ELSEIF E_SAL = 24000 THEN
UPDATE EMPLOYEES SET SALARY = SALARY+0
WHERE EMPLOYEE_ID = E_ID;
ELSE
UPDATE EMPLOYEES SET SALARY = SALARY+500
WHERE EMPLOYEE_ID = E_ID;
END IF;
END LOOP;
CLOSE EMP_CURSOR;
OPEN EMP_CURSOR;
READ_LOOP: LOOP
FETCH EMP_CURSOR INTO E_ID, E_SAL;
IF DONE THEN LEAVE READ_LOOP;
END IF;
IF E_SAL > 5000 THEN
UPDATE EMPLOYEES SET SALARY = SALARY+1000
WHERE EMPLOYEE_ID = E_ID;
ELSEIF E_SAL = 24000 THEN
UPDATE EMPLOYEES SET SALARY = SALARY+0
WHERE EMPLOYEE_ID = E_ID;
ELSE
UPDATE EMPLOYEES SET SALARY = SALARY+500
WHERE EMPLOYEE_ID = E_ID;
END IF;
END LOOP;
CLOSE EMP_CURSOR;
END 
// 
DELIMITER ;
call PROCESS_D();

SELECT * FROM EMPLOYEES;
ROLLBACK;
SELECT * FROM EMPLOYEES;


CREATE TABLE EMP_DATA(EID INT PRIMARY KEY, EMAIL VARCHAR(20) UNIQUE, BDATE DATE NOT NULL, SAL DECIMAL(8, 2) CHECK(SAL > 0), DEPARTMENT_ID INT UNSIGNED,  FOREIGN KEY(DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID));

CREATE TABLE TEMP_SAL (ID INT PRIMARY KEY, SALARY DECIMAL);
INSERT INTO TEMP_SAL VALUES
(1, nULL),
(2, 1431),
(3, 456363);
DELIMITER //
CREATE TRIGGER UP_T
BEFORE UPDATE 
ON TEMP_SAL
FOR EACH ROW 
BEGIN
IF NEW.SALARY < 1000 THEN 
	SET NEW.SALARY = 1000;
ELSEIF NEW.SALARY > 1000 THEN
	SET NEW.SALARY = NEW.SALARY;
END IF;
END
//
DELIMITER ;
UPDATE TEMP_SAL SET SALARY = 500 WHERE ID = 1;
SELECT * FROM TEMP_SAL;

SHOW TRIGGERS;
CREATE TABLE P (P_ID INT PRIMARY KEY, COUNT INT);
CREATE TABLE C (C_ID INT, NAME VARCHAR(50), FOREIGN KEY(C_ID) REFERENCES P(P_ID));
INSERT INTO P VALUES
(1, 0),
(2, 0),
(3,0);
SELECT * FROM P;

CREATE TRIGGER INC_COUNT
AFTER INSERT ON C
FOR EACH ROW
UPDATE P SET COUNT = COUNT+1 WHERE P_ID = NEW.C_ID;

CREATE TRIGGER DEC_COUNT
AFTER DELETE ON C
FOR EACH ROW 
UPDATE P SET COUNT = COUNT-1 WHERE P_ID = OLD.C_ID;


INSERT INTO C VALUES
(1, 'jENIL'),
(2, 'deVASHREE'),
(2, 'Yash');
SELECT * FROM C;

DELETE FROM C WHERE C_ID = 1;
SELECT * FROM C;
SELECT * FROM P;